# Note: This is a sanitized version of the prometheus-config.yaml running on my EC2 instance.

# CHECKLY 
scrape_configs:
  - job_name: 'checkly'
    scrape_interval: 60s
    scheme: https
    metrics_path: '/accounts/METRICS_PATH/v2/prometheus/metrics'
    bearer_token: 'TOKEN'
    static_configs:
      - targets: ['api.checklyhq.com']